service: ssr-lambda-experiment

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: dev-new
  region: eu-west-2

package:
  exclude:
   - src/**
   - node_modules/**
   - firebug-lite/**
   - e2e/**
   - coverage/**
   - '!node_modules/aws-serverless-express/**'

functions:
  ssr:
    handler: ssr-lambda.render
    events:
      - http: ANY {proxy+}
      - http: ANY /